### ISSUE TITLE
Issue related to get(ks: Array[K]): Function to get a value/element from the index based on its key.

### ISSUE THREAD

**Issue by naritapandhe** [quinngroup/python-indexedrdd#1]
get(ks: Array[K]): ks is an array of all the keys whose respective values are to be retrieved.

a) Inorder to get a value with respect to the key, following steps have to be performed:
    1. First perform a groupBy on keys(groupBy on a Collection/List/Array) 
    2. For each of the key, find its partition, rather partitionID
    3. And then get the values from their respective partitions.

b) The existing scala code is as follows:   

```
//Corresponds to Step #1(Mentioned in (a))
val ksByPartition = ks.groupBy(k => partitioner.get.getPartition(k))

//Corresponds to Step #2(Mentioned in (a))
val partitions = ksByPartition.keys.toSeq


//Corresponds to Step #3(Mentioned in (a))
val results: Array[Array[(K, V)]] = context.runJob(partitionsRDD,
  (context: TaskContext, partIter: Iterator[IndexedRDDPartition[K, V]]) => {
    if (partIter.hasNext && ksByPartition.contains(context.partitionId)) {
      val part = partIter.next()
      val ksForPartition = ksByPartition.get(context.partitionId).get
      part.multiget(ksForPartition.iterator).toArray
    } else {
      Array.empty
    }
  }, partitions, allowLocal = true)
results.flatten.toMap
```

c) 
- In Scala, to determine how an RDD is partitioned its partitioner property can be used which returns a spark.Partitioner (https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/Partitioner.scala) object. This object can then be used to invoke the function: getPartition(k)
- getPartition(k) hashes the key against a number(in most cases, the no. of partitions) and returns the hashcode which seems to be the partitionID
- The real problem is that the Python API does not offer any way to access/query partitioners, although it uses them internally.
  This book also mentions the same: https://books.google.com/books?id=2eptBgAAQBAJ&pg=PA64&lpg=PA64&dq=HashPartitioner+python&source=bl&ots=oSuFsk1oN0&sig=BPLbxmDVHoCjEUXiYn37p19HccU&hl=en&sa=X&ved=0ahUKEwiEw8fV_YHLAhVDOCYKHX8aCQUQ6AEISjAH#v=onepage&q=HashPartitioner%20python&f=false

d) So, my question is how can we invoke methods like: getPartition(k) in Python.
The following PythonPartitioner does have the required method, but I am not sure whether its the correct one: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/api/python/PythonPartitioner.scala

**Comment by magsol** [comment]
It looks like this will be another case of having to significantly alter how we do things relative to the Scala API.

(Just FYI: It looks like you may be able to access the low-level Java RDD APIs via `rdd._jrdd`)

The best proxy for now may be [`mapPartitionsWithIndex`](http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.RDD.mapPartitionsWithIndex), specifically setting `preservePartitioning` to `True`. This way it won't alter the partitioning, and you should be able to use the provided index to determine what partition you're on.

**Comment by naritapandhe** [comment]
As you suggested, mapPartitionsWithIndex did let me access the partitionID. 

So, given a key, I find in which partition that (k,v) pair may exists and then return the value associated with the key, if found.
